### ISSUE TITLE
Magento Admin Activity + Inventory Log

### ISSUE THREAD

**Issue by mageuser** [kiwicommerce/magento2-inventory-log#2]
Thanks for your amazing modules, they really help a lot and are very well coded.

In the admin log module we can revert an action, I wonder if it is possible to include this status in the inventory log that the action was reverted by your module.

**Comment by kiwi-commerce** [comment]
Hi @kauansoft  

Thanks for your feedback.
To include the status of third-party extension, we need to do some customisation.

We will add a patch for the third-party module and mention in the documentation.

Thank you.
