### ISSUE TITLE
Not compatible with phpunit/phpunit 6.2

### ISSUE THREAD

**Issue by Tjitse-E** [kiwicommerce/magento2-inventory-log#4]
### Preconditions

1. `phpunit/phpunit` 6.2.x
2. Magento 2.2.x

### Steps to reproduce

1. Install Magento 2.2.x
2. Install the module `kiwicommerce/magento2-inventory-log`
3. Run phpunit

### Expected result

1. The unit tests of `kiwicommerce/module-inventory-log` should pass

### Actual result

1. Erorr when running PHPunit: 
```
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in vendor/kiwicommerce/module-inventory-log/Test/Unit/Helper/DataTest.php on line 16
```

The unit tests aren't updated to work with the PHP unit version used with Magento 2.2.

**Comment by kiwi-commerce** [comment]
Hi @Tjitse-E. Thank you for your report. We will have a look over this query.

**Comment by kiwi-commerce** [comment]
Hi @Tjitse-E . Thank you for your report.
The issue has been fixed
Related commit(s):
- [ece399e423fa8b7ac6f27dcf1a993b2a97b5fe84](https://github.com/kiwicommerce/magento2-inventory-log/commit/ece399e423fa8b7ac6f27dcf1a993b2a97b5fe84)

The fix will be available with the upcoming release.
