### ISSUE TITLE
Error - setup:upgrade

### ISSUE THREAD

**Issue by simonemonterubbiano** [kiwicommerce/magento2-inventory-log#5]
To reproduce this issue you have to set index to schedule mode:

php bin/magento indexer:set-mode schedule

_Originally posted by @simonemonterubbiano in https://github.com/kiwicommerce/magento2-inventory-log/issues/3#issuecomment-439452652_

**Comment by kiwi-commerce** [comment]
Hi @simonemonterubbiano 

Thanks for reporting the issue.
We will check it and back to you.

**Comment by gotanasro3** [comment]
I have the same problem on magento 2.3.3

Is there a solution?

**Comment by kiwi-commerce** [comment]
Hello,

I’d recommend you to use the MySQL version that supports the multiple triggers then the extension will work properly.

We are using MySQL triggers to monitor stock update while bulk product import or direct changes to the stock table are processed. In that case, the observers are not executed.

Feel free to re-open this issue if found any other problem.

Thank you.
