### ISSUE TITLE
Admin create order not logged

### ISSUE THREAD

**Issue by VaporFan** [kiwicommerce/magento2-inventory-log#6]
Hello,
I have just installed the ext on my magento 2.2.6. It seems only log my manual changes of stock qty. When I create an order from Admin, then complete the order, there's nothing logged. I'm using Flat Catalog.

**Comment by kiwi-commerce** [comment]
Hello @VaporFan ,

We can not reproduce this issue.

If you still get an issue, then please contact us on https://kiwicommerce.co.uk/get-in-touch/.

Thank you.
